opam-version: "2.0"
maintainer: "Robur <team@robur.coop>"
authors: ["Robur <team@robur.coop>"]
homepage: "https://github.com/robur-coop/immuable"
dev-repo: "git+https://github.com/robur-coop/immuable.git"
bug-reports: "https://github.com/robur-coop/immuable/issues"
license: "MIT"

depends: [
  "ocaml" {>= "5.3.0"}
  "dune" {>= "3.0.0"}
  "vif"
  "mirage-crypto-rng-mkernel"
  "vifu"
  "brr"
  "progress"
  "flux"
  "carton"
  "art"
  "encore"
  "cattery"
  "mcrunch"
  "emile"
  "rosetta"
]
build: [
  [make "all"]
]
synopsis: "An unikernel which serve HTTP contents"
pin-depends: [
  [ "vif.dev"             "git+https://github.com/robur-coop/vif.git#8c6ac3fb97cb9a31bf6ad8ec63c942336dcfd03e" ]
  [ "vifu.dev"            "git+https://github.com/robur-coop/vif.git#8c6ac3fb97cb9a31bf6ad8ec63c942336dcfd03e" ]
  [ "cattery.dev"         "git+https://git.robur.coop/robur/cattery.git#d0ce64092a381ef8491172fe4587dc1fc4736e33" ]
  [ "zarith.dev"          "git+https://github.com/mirage/Zarith.git#df8969d9bb95cffca13e31a615189ab27ada0684" ]
  [ "httpcats.dev"        "git+https://github.com/robur-coop/httpcats.git#75991cc9522fcb96851d19ceda6edc85d447386a" ]
  [ "mhttp.dev"           "git+https://github.com/robur-coop/mhttp.git#b2e55ae693b07ad3ef87c26c37c8f5d14c2e205c" ]
  [ "mhttp-server.dev"    "git+https://github.com/robur-coop/mhttp.git#b2e55ae693b07ad3ef87c26c37c8f5d14c2e205c" ]
  [ "mhttp-client.dev"    "git+https://github.com/robur-coop/mhttp.git#b2e55ae693b07ad3ef87c26c37c8f5d14c2e205c" ]
  [ "blaze.dev"           "git+https://github.com/dinosaure/blaze.git#fb7de04ace818437a2f49423b7edc2541ae4a614" ]
  [ "maildir.dev"         "git+https://github.com/dinosaure/ocaml-maildir.git#597823c7d2d4fd2aef26a581f6828f2b458371ea" ]
  [ "stem.dev"            "git+https://github.com/robur-coop/stem.git#66ce4f85ec2ad317ef2bd01bad71c93c0af68210" ]
  [ "bm25.dev"            "git+https://github.com/robur-coop/stem.git#66ce4f85ec2ad317ef2bd01bad71c93c0af68210" ]
  [ "mrmime.dev"          "git+https://github.com/mirage/mrmime.git#ffce7951d3df81d5555c0686489535e21e6443da" ]
  [ "dkim.dev"            "git+https://github.com/mirage/ocaml-dkim.git#e9c8d76e6cf3bd75c0d133694c082c433e8ae342" ]
]
