opam-version: "2.0"
maintainer: "Robur <team@robur.coop>"
authors: ["Robur <team@robur.coop>"]
homepage: "https://github.com/robur-coop/blame"
dev-repo: "git+https://github.com/robur-coop/blame.git"
bug-reports: "https://github.com/robur-coop/blame/issues"
license: "MIT"

depends: [
  "ocaml" {>= "5.3.0"}
  "dune" {>= "3.0.0"}
  "vif" {= version}
  "mhttp"
  "mirage-crypto-rng-mkernel"
  "emile"
  "cmdliner"
  "logs"
  "fmt"
  "fpath"
  "hxd"
  "gmp"
  "jsont"
  "digestif"
  "rosetta"
  "encore"
  "vifu"
]
conflicts: [ "result" {< "1.5"} ]
build: [
  ["dune" "subst"] {dev}
  ["./source.sh"]
  ["dune" "build" "-p" name "-j" jobs]
  ["./install.sh"]
]
synopsis: "A self-contained unikernel to provide a search engine from an archive of emails"
x-ci-accept-failures: ["debian-11"]
pin-depends: [
  [ "mirage-crypto.2.0.2" "git+https://github.com/dinosaure/mirage-crypto.git#820db4c1d19acd06dca82ce5615904848a852951" ]
  [ "mirage-crypto-ec.2.0.2" "git+https://github.com/dinosaure/mirage-crypto.git#820db4c1d19acd06dca82ce5615904848a852951" ]
  [ "mirage-crypto-pk.2.0.2" "git+https://github.com/dinosaure/mirage-crypto.git#820db4c1d19acd06dca82ce5615904848a852951" ]
  [ "mirage-crypto-rng.2.0.2" "git+https://github.com/dinosaure/mirage-crypto.git#820db4c1d19acd06dca82ce5615904848a852951" ]
  [ "mirage-crypto-rng-miou-unix.2.0.2" "git+https://github.com/dinosaure/mirage-crypto.git#820db4c1d19acd06dca82ce5615904848a852951" ]
  [ "mirage-crypto-rng-mkernel.2.0.2" "git+https://github.com/dinosaure/mirage-crypto.git#820db4c1d19acd06dca82ce5615904848a852951" ]
  [ "mkernel.dev" "git+https://github.com/robur-coop/mkernel.git#e5259f1a98f0afacb5bca646e5fde176f0c8fb26" ]
  [ "mnet.dev" "git+https://git.robur.coop/robur/mnet.git#4c390387c37e7ca2953397f008eda975ed727dce" ]
  [ "vif.dev" "git+https://git.robur.coop/robur/vif.git#ce0136481e6c19322bdbadd96720dec43453a1d1" ]
  [ "vifu.dev" "git+https://git.robur.coop/robur/vif.git#ce0136481e6c19322bdbadd96720dec43453a1d1" ]
  [ "utcp.dev" "git+https://github.com/robur-coop/utcp.git#854082cf3a45053e0c308faa6dfc84d7735d1ec6" ]
  [ "carton.dev" "git+https://github.com/robur-coop/carton.git#f3d9d905d8de849a660b3ec8193c791bfb655918" ]
  [ "carton-miou.dev" "git+https://github.com/robur-coop/carton.git#f3d9d905d8de849a660b3ec8193c791bfb655918" ]
  [ "flux.dev" "git+https://github.com/robur-coop/flux.git#731979220bb856abf370654748c6da72f320a4ef" ]
  [ "fluxt.dev" "git+https://github.com/robur-coop/flux.git#731979220bb856abf370654748c6da72f320a4ef" ]
  [ "mhttp.dev" "git+https://github.com/dinosaure/mhttp.git#2cbbdf376be7cda5dba70fe673d5e0895c16f5be" ]
  [ "stem.dev" "git+https://github.com/robur-coop/stem.git#22a9588d0090c151c6905d721a533177dd92a4bc" ]
  [ "bm25.dev" "git+https://github.com/robur-coop/stem.git#22a9588d0090c151c6905d721a533177dd92a4bc" ]
  [ "blaze.dev" "git+https://github.com/dinosaure/blaze.git#99a8ddaa84059c67df4ed5527eff58cbb39dcdb0" ]
  [ "maildir.dev" "git+https://github.com/dinosaure/ocaml-maildir.git#597823c7d2d4fd2aef26a581f6828f2b458371ea" ]
  [ "httpcats.dev" "git+https://github.com/robur-coop/httpcats.git#c107a79119562248bfd0513c80c4990eff4b4994" ]
]
