(executable
 (name main)
 (modules main documents)
 (public_name blame)
 (link_flags :standard -cclib "-z solo5-abi=hvt")
 (libraries
  blame.emails
  blaze.stem
  stem.tokenizer
  stem.snowball
  stem.stopwords
  gmp
  mirage-crypto-rng-mkernel
  trie
  vifu
  cattery)
 (foreign_stubs
  (language c)
  (names manifest)))

(executable
 (name script)
 (modules script)
 (modes js)
 (libraries jsont.brr brr lru blame.format))

(rule
 (targets script.js)
 (deps script.bc.js)
 (action
  (copy script.bc.js script.js)))

(library
 (name format)
 (public_name blame.format)
 (modules format)
 (libraries fmt rosetta emile ptime jsont))

(library
 (name emails)
 (public_name blame.emails)
 (modules emails)
 (libraries
  blame.format
  jsont
  hxd.core
  hxd.string
  emile
  blaze.email
  blaze.stem
  digestif
  mkernel
  carton-miou.flux
  cattery))

(rule
 (targets manifest.c)
 (enabled_if
  (= %{context_name} "default"))
 (action
  (write-file manifest.c "")))

(rule
 (targets manifest.c)
 (deps manifest.json)
 (enabled_if
  (= %{context_name} "solo5"))
 (action
  (run solo5-elftool gen-manifest manifest.json manifest.c)))

(rule
 (targets documents.ml)
 (deps index.html script.js style.css email.html)
 (action
  (with-stdout-to
   documents.ml
   (run
    mcrunch
    --file
    index:index.html
    --file
    script:script.js
    --file
    style:style.css
    --file
    email:email.html))))

(vendored_dirs vendors)
